version: '2'

services:
  nginx:
    image: 'swenum/nginx:41'
    volumes:
      - ./conf/wordpress.swn.by:/etc/nginx/conf.d/wordpress.swn.by.conf:ro
      - ./www:/app
    ports:
        - '8089:80'
  php:
    image: 'swenum/fpm:41'
    ports:
      - '9000:9000'
    volumes:
      - ./www:/var/www/html
  mariadb:
    image: 'swenum/mysql:41'
    volumes:
      - ./data:/var/lib/mysql:rw
    ports:
      - '3336:3306'
      