version: '2'

services:
  nginx:
    build: .
    ports:
      - '8081:80'
      
    volumes:
      - ./www:/app
      - ./conf/wordpress.swn.by:/etc/nginx/sites-enabled/wordpress.swn.by.conf:ro
      - ./logs:/opt/bitnami/nginx/logs:rw
  php:
    build: ../php/
    ports:
      - '9000:9000'
      
    volumes:
      - ./www:/var/www/html
  mariadb:
    image: 'swenum/mysql:35'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ../mariadb/data:/var/lib/mysql:rw
    ports:
      - '3306:3306'
      