version: '2'

services:
  nginx:
    image: 'swenum/nginx:35'
    volumes:
      - ./conf:/etc/nginx/conf.d/wordpress.swn.by
      - ./www:/var/www/html
    ports:
        - '8089:80'
  php:
    image: 'swenum/fpm:35'
    ports:
      - '9000:9000'
    volumes:
      - ./www:/var/www/html
  mariadb:
    image: 'swenum/mysql:35'
    volumes:
      - ./data:/var/lib/mysql:rw
    ports:
      - '3336:3306'
      