version: '2'

services:
  nginx:
    image: 'swenum/nginx:44'
    volumes:
      - /docker/ci_pipeline/nginx/conf/wordpress.swn.by:/opt/bitnami/nginx/conf/server_blocks/wordpress.swn.by.conf:ro
      - /docker/ci_pipeline/nginx/www:/app
    ports:
        - '8089:80'
  php:
    image: 'swenum/fpm:44'
    ports:
      - '9000:9000'
    volumes:
      - ./www:/var/www/html
  mariadb:
    image: 'swenum/mysql:44'
    volumes:
      - ./data:/var/lib/mysql:rw
    ports:
      - '3336:3306'

# docker run  -p 8057:80 -v /docker/ci_pipeline/nginx/www:/app -v /docker/ci_pipeline/nginx/www:/app   -v /docker/ci_pipeline/nginx/conf/wordpress.swn.by:/opt/bitnami/nginx/conf/server_blocks/wordpress.swn.by.conf:ro       swenum/nginx:44
      