version: '2'

services:
  nginx:
    image: 'swenum/nginx:35'
    ports:
      - '8081:80'
      
    volumes:
      - ./www:/app
      - ./conf/wordpress.swn.by:/etc/nginx/sites-enabled/wordpress.swn.by.conf:ro
      - ./logs:/opt/bitnami/nginx/logs:rw
  php:
    image: 'swenum/fpm:35'
    ports:
      - '9000:9000'
      
    volumes:
      - ./www:/var/www/html
  mariadb:
    image: 'swenum/mysql:35'
    volumes:
      - ./data:/var/lib/mysql:rw
    ports:
      - '3306:3306'
      