FROM bitnami/nginx
MAINTAINER Andrei Dets 'fatum@tut.by'

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

#COPY ./nginx.conf /etc/nginx/nginx.conf
#COPY ./wordpress.conf /etc/nginx/conf.d/wordpress.conf
#COPY ./index.html /var/www/html/index.html
EXPOSE 80
